on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'asc70'
          server: 'srcf.net'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: '/home/arthur/public_html'
          remote_path: '/public_html'
          args: '-o ConnectTimeout=5'
