name: CI
on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH to pip
        if: github.ref == 'refs/heads/release'
        run: |
          umask 0077
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          echo "${{ secrets.SSH_HOST_KEY }}" > $HOME/.ssh/known_hosts
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} /path/to/upgrade/script.sh
